Update healthcheck

diff --git a/bin/chuspace/cmds/healthcheck b/bin/chuspace/cmds/healthcheck
--- a/bin/chuspace/cmds/healthcheck
+++ b/bin/chuspace/cmds/healthcheck
@@ -4,10 +4,30 @@
 
 case $ENVIRONMENT in
   production)
-    until curl -s -f -o /dev/null "https://chuspace.com/heartbeat"
+    fail_count=1
+
+    while true
     do
-      echo 'Production not deployed. Sleeping 5 seconds'
-      sleep 5
+      response=$(curl --write-out %{http_code} --silent --output /dev/null $1)
+
+      if [ $response -eq 200 ] ; then
+        echo "$(date -u) Server available"
+        # wait for loadbalancer to register
+
+        echo "$(date -u) Waiting for Droplet to register with LB"
+        sleep 60
+
+        exit 0
+      else
+        if [ $fail_count -eq 11 ]; then
+          echo "$(date -u) Server unavailable"
+          exit 2
+        else
+          echo "$(date -u) Attempt ${fail_count}/10: Server not yet available"
+          sleep 3
+          fail_count=$[$fail_count +1]
+        fi
+      fi
     done
     ;;
   *)
